// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :exec
UPDATE invitations
SET
    accepted_at = NOW()
WHERE
    id = $1
`

func (q *Queries) AcceptInvitation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, acceptInvitation, id)
	return err
}

const addOrganizationMember = `-- name: AddOrganizationMember :one
INSERT INTO
    organization_members (organization_id, user_id, role)
VALUES
    ($1, $2, $3)
RETURNING
    organization_id, user_id, role, created_at
`

type AddOrganizationMemberParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
	Role           UserRole    `json:"role"`
}

func (q *Queries) AddOrganizationMember(ctx context.Context, arg AddOrganizationMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, addOrganizationMember, arg.OrganizationID, arg.UserID, arg.Role)
	var i OrganizationMember
	err := row.Scan(
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO
    invitations (
        organization_id,
        email,
        name,
        role,
        token_hash,
        expires_at
    )
VALUES
    ($1, $2, $3, $4, $5, $6)
RETURNING
    id, organization_id, email, name, role, token_hash, expires_at, accepted_at, created_at
`

type CreateInvitationParams struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Email          string             `json:"email"`
	Name           string             `json:"name"`
	Role           UserRole           `json:"role"`
	TokenHash      string             `json:"token_hash"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.OrganizationID,
		arg.Email,
		arg.Name,
		arg.Role,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO
    organizations (name, domain)
VALUES
    ($1, $2)
RETURNING
    id, name, domain, created_at
`

type CreateOrganizationParams struct {
	Name   string      `json:"name"`
	Domain pgtype.Text `json:"domain"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Domain)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO
    sessions (user_id, token_hash, expires_at)
VALUES
    ($1, $2, $3)
RETURNING
    id, user_id, token_hash, expires_at, created_at
`

type CreateSessionParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (email, name, password_hash)
VALUES
    ($1, $2, $3)
RETURNING
    id, email, name, password_hash, is_active, created_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	Name         string      `json:"name"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE
    expires_at <= NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE
    token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
SELECT
    id, organization_id, email, name, role, token_hash, expires_at, accepted_at, created_at
FROM
    invitations
WHERE
    token_hash = $1
    AND accepted_at IS NULL
    AND expires_at > NOW()
LIMIT
    1
`

func (q *Queries) GetInvitationByTokenHash(ctx context.Context, tokenHash string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenHash, tokenHash)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT
    u.id AS user_id,
    u.email,
    u.name,
    u.is_active,
    om.organization_id,
    om.role
FROM
    sessions s
    JOIN users u ON u.id = s.user_id
    JOIN organization_members om ON om.user_id = u.id
WHERE
    s.token_hash = $1
    AND s.expires_at > NOW()
    AND u.is_active = TRUE
LIMIT
    1
`

type GetSessionUserRow struct {
	UserID         pgtype.UUID `json:"user_id"`
	Email          string      `json:"email"`
	Name           string      `json:"name"`
	IsActive       bool        `json:"is_active"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Role           UserRole    `json:"role"`
}

func (q *Queries) GetSessionUser(ctx context.Context, tokenHash string) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i GetSessionUserRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Name,
		&i.IsActive,
		&i.OrganizationID,
		&i.Role,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT
    id, email, name, password_hash, is_active, created_at
FROM
    users
WHERE
    id = $1
LIMIT
    1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id, email, name, password_hash, is_active, created_at
FROM
    users
WHERE
    email = $1
LIMIT
    1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserWithOrganization = `-- name: GetUserWithOrganization :one
SELECT
    u.id AS user_id,
    u.email,
    u.name,
    u.password_hash,
    u.is_active,
    om.organization_id,
    om.role
FROM
    users u
    JOIN organization_members om ON om.user_id = u.id
WHERE
    u.id = $1
LIMIT
    1
`

type GetUserWithOrganizationRow struct {
	UserID         pgtype.UUID `json:"user_id"`
	Email          string      `json:"email"`
	Name           string      `json:"name"`
	PasswordHash   pgtype.Text `json:"password_hash"`
	IsActive       bool        `json:"is_active"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Role           UserRole    `json:"role"`
}

func (q *Queries) GetUserWithOrganization(ctx context.Context, id pgtype.UUID) (GetUserWithOrganizationRow, error) {
	row := q.db.QueryRow(ctx, getUserWithOrganization, id)
	var i GetUserWithOrganizationRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsActive,
		&i.OrganizationID,
		&i.Role,
	)
	return i, err
}

const listOrganizationMembers = `-- name: ListOrganizationMembers :many
SELECT
    u.id,
    u.email,
    u.name,
    u.is_active,
    om.role,
    om.created_at
FROM
    organization_members om
    JOIN users u ON u.id = om.user_id
WHERE
    om.organization_id = $1
ORDER BY
    om.created_at DESC
`

type ListOrganizationMembersRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	IsActive  bool               `json:"is_active"`
	Role      UserRole           `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListOrganizationMembers(ctx context.Context, organizationID pgtype.UUID) ([]ListOrganizationMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationMembers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationMembersRow{}
	for rows.Next() {
		var i ListOrganizationMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.IsActive,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    name = COALESCE($2, name),
    is_active = COALESCE($3, is_active)
WHERE
    id = $1
RETURNING
    id, email, name, password_hash, is_active, created_at
`

type UpdateUserParams struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Name, arg.IsActive)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE organization_members
SET role = $3
WHERE
    organization_id = $1
    AND user_id = $2
`

type UpdateUserRoleParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
	Role           UserRole    `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.OrganizationID, arg.UserID, arg.Role)
	return err
}
