// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meetings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMeeting = `-- name: CreateMeeting :one
INSERT INTO
    meetings (
        title,
        started_at,
        ended_at,
        duration_seconds,
        audio_path,
        video_path
    )
VALUES
    ($1, $2, $3, $4, $5, $6)
RETURNING
    id, title, started_at, ended_at, duration_seconds, audio_path, video_path, created_at, updated_at
`

type CreateMeetingParams struct {
	Title           string             `json:"title"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
	DurationSeconds pgtype.Float8      `json:"duration_seconds"`
	AudioPath       pgtype.Text        `json:"audio_path"`
	VideoPath       pgtype.Text        `json:"video_path"`
}

// db/queries/meetings.sql
func (q *Queries) CreateMeeting(ctx context.Context, arg CreateMeetingParams) (Meeting, error) {
	row := q.db.QueryRow(ctx, createMeeting,
		arg.Title,
		arg.StartedAt,
		arg.EndedAt,
		arg.DurationSeconds,
		arg.AudioPath,
		arg.VideoPath,
	)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.AudioPath,
		&i.VideoPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMeetingActionItem = `-- name: CreateMeetingActionItem :one
INSERT INTO
    meeting_action_items (meeting_id, task, assignee, timestamp_seconds)
VALUES
    ($1, $2, $3, $4)
RETURNING
    id, meeting_id, task, assignee, timestamp_seconds, completed, created_at
`

type CreateMeetingActionItemParams struct {
	MeetingID        pgtype.UUID `json:"meeting_id"`
	Task             string      `json:"task"`
	Assignee         pgtype.Text `json:"assignee"`
	TimestampSeconds float64     `json:"timestamp_seconds"`
}

func (q *Queries) CreateMeetingActionItem(ctx context.Context, arg CreateMeetingActionItemParams) (MeetingActionItem, error) {
	row := q.db.QueryRow(ctx, createMeetingActionItem,
		arg.MeetingID,
		arg.Task,
		arg.Assignee,
		arg.TimestampSeconds,
	)
	var i MeetingActionItem
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.Task,
		&i.Assignee,
		&i.TimestampSeconds,
		&i.Completed,
		&i.CreatedAt,
	)
	return i, err
}

const createMeetingDecision = `-- name: CreateMeetingDecision :one
INSERT INTO
    meeting_decisions (meeting_id, decision, timestamp_seconds)
VALUES
    ($1, $2, $3)
RETURNING
    id, meeting_id, decision, timestamp_seconds, created_at
`

type CreateMeetingDecisionParams struct {
	MeetingID        pgtype.UUID `json:"meeting_id"`
	Decision         string      `json:"decision"`
	TimestampSeconds float64     `json:"timestamp_seconds"`
}

func (q *Queries) CreateMeetingDecision(ctx context.Context, arg CreateMeetingDecisionParams) (MeetingDecision, error) {
	row := q.db.QueryRow(ctx, createMeetingDecision, arg.MeetingID, arg.Decision, arg.TimestampSeconds)
	var i MeetingDecision
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.Decision,
		&i.TimestampSeconds,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMeeting = `-- name: DeleteMeeting :exec
DELETE FROM meetings
WHERE
    id = $1
`

func (q *Queries) DeleteMeeting(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMeeting, id)
	return err
}

const deleteMeetingActionItem = `-- name: DeleteMeetingActionItem :exec
DELETE FROM meeting_action_items
WHERE
    id = $1
`

func (q *Queries) DeleteMeetingActionItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMeetingActionItem, id)
	return err
}

const deleteMeetingActionItems = `-- name: DeleteMeetingActionItems :exec
DELETE FROM meeting_action_items
WHERE
    meeting_id = $1
`

func (q *Queries) DeleteMeetingActionItems(ctx context.Context, meetingID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMeetingActionItems, meetingID)
	return err
}

const deleteMeetingDecision = `-- name: DeleteMeetingDecision :exec
DELETE FROM meeting_decisions
WHERE
    id = $1
`

func (q *Queries) DeleteMeetingDecision(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMeetingDecision, id)
	return err
}

const deleteMeetingDecisions = `-- name: DeleteMeetingDecisions :exec
DELETE FROM meeting_decisions
WHERE
    meeting_id = $1
`

func (q *Queries) DeleteMeetingDecisions(ctx context.Context, meetingID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMeetingDecisions, meetingID)
	return err
}

const getMeeting = `-- name: GetMeeting :one
SELECT
    id, title, started_at, ended_at, duration_seconds, audio_path, video_path, created_at, updated_at
FROM
    meetings
WHERE
    id = $1
LIMIT
    1
`

func (q *Queries) GetMeeting(ctx context.Context, id pgtype.UUID) (Meeting, error) {
	row := q.db.QueryRow(ctx, getMeeting, id)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.AudioPath,
		&i.VideoPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMeetingActionItem = `-- name: GetMeetingActionItem :one
SELECT
    id, meeting_id, task, assignee, timestamp_seconds, completed, created_at
FROM
    meeting_action_items
WHERE
    id = $1
LIMIT
    1
`

func (q *Queries) GetMeetingActionItem(ctx context.Context, id pgtype.UUID) (MeetingActionItem, error) {
	row := q.db.QueryRow(ctx, getMeetingActionItem, id)
	var i MeetingActionItem
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.Task,
		&i.Assignee,
		&i.TimestampSeconds,
		&i.Completed,
		&i.CreatedAt,
	)
	return i, err
}

const getMeetingDecision = `-- name: GetMeetingDecision :one
SELECT
    id, meeting_id, decision, timestamp_seconds, created_at
FROM
    meeting_decisions
WHERE
    id = $1
LIMIT
    1
`

func (q *Queries) GetMeetingDecision(ctx context.Context, id pgtype.UUID) (MeetingDecision, error) {
	row := q.db.QueryRow(ctx, getMeetingDecision, id)
	var i MeetingDecision
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.Decision,
		&i.TimestampSeconds,
		&i.CreatedAt,
	)
	return i, err
}

const listIncompleteActionItems = `-- name: ListIncompleteActionItems :many
SELECT
    id, meeting_id, task, assignee, timestamp_seconds, completed, created_at
FROM
    meeting_action_items
WHERE
    meeting_id = $1
    AND completed = FALSE
ORDER BY
    timestamp_seconds ASC
`

func (q *Queries) ListIncompleteActionItems(ctx context.Context, meetingID pgtype.UUID) ([]MeetingActionItem, error) {
	rows, err := q.db.Query(ctx, listIncompleteActionItems, meetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MeetingActionItem{}
	for rows.Next() {
		var i MeetingActionItem
		if err := rows.Scan(
			&i.ID,
			&i.MeetingID,
			&i.Task,
			&i.Assignee,
			&i.TimestampSeconds,
			&i.Completed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeetingActionItems = `-- name: ListMeetingActionItems :many
SELECT
    id, meeting_id, task, assignee, timestamp_seconds, completed, created_at
FROM
    meeting_action_items
WHERE
    meeting_id = $1
ORDER BY
    timestamp_seconds ASC
`

func (q *Queries) ListMeetingActionItems(ctx context.Context, meetingID pgtype.UUID) ([]MeetingActionItem, error) {
	rows, err := q.db.Query(ctx, listMeetingActionItems, meetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MeetingActionItem{}
	for rows.Next() {
		var i MeetingActionItem
		if err := rows.Scan(
			&i.ID,
			&i.MeetingID,
			&i.Task,
			&i.Assignee,
			&i.TimestampSeconds,
			&i.Completed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeetingDecisions = `-- name: ListMeetingDecisions :many
SELECT
    id, meeting_id, decision, timestamp_seconds, created_at
FROM
    meeting_decisions
WHERE
    meeting_id = $1
ORDER BY
    timestamp_seconds ASC
`

func (q *Queries) ListMeetingDecisions(ctx context.Context, meetingID pgtype.UUID) ([]MeetingDecision, error) {
	rows, err := q.db.Query(ctx, listMeetingDecisions, meetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MeetingDecision{}
	for rows.Next() {
		var i MeetingDecision
		if err := rows.Scan(
			&i.ID,
			&i.MeetingID,
			&i.Decision,
			&i.TimestampSeconds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeetings = `-- name: ListMeetings :many
SELECT
    id, title, started_at, ended_at, duration_seconds, audio_path, video_path, created_at, updated_at
FROM
    meetings
ORDER BY
    created_at DESC
`

func (q *Queries) ListMeetings(ctx context.Context) ([]Meeting, error) {
	rows, err := q.db.Query(ctx, listMeetings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Meeting{}
	for rows.Next() {
		var i Meeting
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSeconds,
			&i.AudioPath,
			&i.VideoPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeetingsWithDecisionsAndActionItems = `-- name: ListMeetingsWithDecisionsAndActionItems :many
SELECT
    meetings.id, title, started_at, ended_at, duration_seconds, audio_path, video_path, meetings.created_at, updated_at, meeting_decisions.id, meeting_decisions.meeting_id, decision, meeting_decisions.timestamp_seconds, meeting_decisions.created_at, meeting_action_items.id, meeting_action_items.meeting_id, task, assignee, meeting_action_items.timestamp_seconds, completed, meeting_action_items.created_at
FROM
    meetings
    JOIN meeting_decisions ON meetings.id = meeting_decisions.meeting_id
    JOIN meeting_action_items ON meetings.id = meeting_action_items.meeting_id
ORDER BY
    meetings.created_at DESC
`

type ListMeetingsWithDecisionsAndActionItemsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Title              string             `json:"title"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	EndedAt            pgtype.Timestamptz `json:"ended_at"`
	DurationSeconds    pgtype.Float8      `json:"duration_seconds"`
	AudioPath          pgtype.Text        `json:"audio_path"`
	VideoPath          pgtype.Text        `json:"video_path"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ID_2               pgtype.UUID        `json:"id_2"`
	MeetingID          pgtype.UUID        `json:"meeting_id"`
	Decision           string             `json:"decision"`
	TimestampSeconds   float64            `json:"timestamp_seconds"`
	CreatedAt_2        pgtype.Timestamptz `json:"created_at_2"`
	ID_3               pgtype.UUID        `json:"id_3"`
	MeetingID_2        pgtype.UUID        `json:"meeting_id_2"`
	Task               string             `json:"task"`
	Assignee           pgtype.Text        `json:"assignee"`
	TimestampSeconds_2 float64            `json:"timestamp_seconds_2"`
	Completed          bool               `json:"completed"`
	CreatedAt_3        pgtype.Timestamptz `json:"created_at_3"`
}

func (q *Queries) ListMeetingsWithDecisionsAndActionItems(ctx context.Context) ([]ListMeetingsWithDecisionsAndActionItemsRow, error) {
	rows, err := q.db.Query(ctx, listMeetingsWithDecisionsAndActionItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMeetingsWithDecisionsAndActionItemsRow{}
	for rows.Next() {
		var i ListMeetingsWithDecisionsAndActionItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSeconds,
			&i.AudioPath,
			&i.VideoPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ID_2,
			&i.MeetingID,
			&i.Decision,
			&i.TimestampSeconds,
			&i.CreatedAt_2,
			&i.ID_3,
			&i.MeetingID_2,
			&i.Task,
			&i.Assignee,
			&i.TimestampSeconds_2,
			&i.Completed,
			&i.CreatedAt_3,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markActionItemCompleted = `-- name: MarkActionItemCompleted :one
UPDATE meeting_action_items
SET
    completed = TRUE
WHERE
    id = $1
RETURNING
    id, meeting_id, task, assignee, timestamp_seconds, completed, created_at
`

func (q *Queries) MarkActionItemCompleted(ctx context.Context, id pgtype.UUID) (MeetingActionItem, error) {
	row := q.db.QueryRow(ctx, markActionItemCompleted, id)
	var i MeetingActionItem
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.Task,
		&i.Assignee,
		&i.TimestampSeconds,
		&i.Completed,
		&i.CreatedAt,
	)
	return i, err
}

const markActionItemIncomplete = `-- name: MarkActionItemIncomplete :one
UPDATE meeting_action_items
SET
    completed = FALSE
WHERE
    id = $1
RETURNING
    id, meeting_id, task, assignee, timestamp_seconds, completed, created_at
`

func (q *Queries) MarkActionItemIncomplete(ctx context.Context, id pgtype.UUID) (MeetingActionItem, error) {
	row := q.db.QueryRow(ctx, markActionItemIncomplete, id)
	var i MeetingActionItem
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.Task,
		&i.Assignee,
		&i.TimestampSeconds,
		&i.Completed,
		&i.CreatedAt,
	)
	return i, err
}

const updateMeeting = `-- name: UpdateMeeting :one
UPDATE meetings
SET
    title = $2,
    started_at = $3,
    ended_at = $4,
    duration_seconds = $5,
    audio_path = $6,
    video_path = $7,
    updated_at = NOW()
WHERE
    id = $1
RETURNING
    id, title, started_at, ended_at, duration_seconds, audio_path, video_path, created_at, updated_at
`

type UpdateMeetingParams struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
	DurationSeconds pgtype.Float8      `json:"duration_seconds"`
	AudioPath       pgtype.Text        `json:"audio_path"`
	VideoPath       pgtype.Text        `json:"video_path"`
}

func (q *Queries) UpdateMeeting(ctx context.Context, arg UpdateMeetingParams) (Meeting, error) {
	row := q.db.QueryRow(ctx, updateMeeting,
		arg.ID,
		arg.Title,
		arg.StartedAt,
		arg.EndedAt,
		arg.DurationSeconds,
		arg.AudioPath,
		arg.VideoPath,
	)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.AudioPath,
		&i.VideoPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMeetingActionItem = `-- name: UpdateMeetingActionItem :one
UPDATE meeting_action_items
SET
    task = $2,
    assignee = $3,
    timestamp_seconds = $4,
    completed = $5
WHERE
    id = $1
RETURNING
    id, meeting_id, task, assignee, timestamp_seconds, completed, created_at
`

type UpdateMeetingActionItemParams struct {
	ID               pgtype.UUID `json:"id"`
	Task             string      `json:"task"`
	Assignee         pgtype.Text `json:"assignee"`
	TimestampSeconds float64     `json:"timestamp_seconds"`
	Completed        bool        `json:"completed"`
}

func (q *Queries) UpdateMeetingActionItem(ctx context.Context, arg UpdateMeetingActionItemParams) (MeetingActionItem, error) {
	row := q.db.QueryRow(ctx, updateMeetingActionItem,
		arg.ID,
		arg.Task,
		arg.Assignee,
		arg.TimestampSeconds,
		arg.Completed,
	)
	var i MeetingActionItem
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.Task,
		&i.Assignee,
		&i.TimestampSeconds,
		&i.Completed,
		&i.CreatedAt,
	)
	return i, err
}
