// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Meeting struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
	DurationSeconds pgtype.Float8      `json:"duration_seconds"`
	AudioPath       pgtype.Text        `json:"audio_path"`
	VideoPath       pgtype.Text        `json:"video_path"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type MeetingActionItem struct {
	ID               pgtype.UUID        `json:"id"`
	MeetingID        pgtype.UUID        `json:"meeting_id"`
	Task             string             `json:"task"`
	Assignee         pgtype.Text        `json:"assignee"`
	TimestampSeconds float64            `json:"timestamp_seconds"`
	Completed        bool               `json:"completed"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type MeetingDecision struct {
	ID               pgtype.UUID        `json:"id"`
	MeetingID        pgtype.UUID        `json:"meeting_id"`
	Decision         string             `json:"decision"`
	TimestampSeconds float64            `json:"timestamp_seconds"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type TranscriptSegment struct {
	ID        pgtype.UUID        `json:"id"`
	MeetingID pgtype.UUID        `json:"meeting_id"`
	StartTime float64            `json:"start_time"`
	EndTime   float64            `json:"end_time"`
	Speaker   string             `json:"speaker"`
	Text      string             `json:"text"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
