// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type UserRole string

const (
	UserRoleOwner  UserRole = "owner"
	UserRoleAdmin  UserRole = "admin"
	UserRoleMember UserRole = "member"
	UserRoleViewer UserRole = "viewer"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Invitation struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Email          string             `json:"email"`
	Name           string             `json:"name"`
	Role           UserRole           `json:"role"`
	TokenHash      string             `json:"token_hash"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt     pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Meeting struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
	DurationSeconds pgtype.Float8      `json:"duration_seconds"`
	AudioPath       pgtype.Text        `json:"audio_path"`
	VideoPath       pgtype.Text        `json:"video_path"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Summary         pgtype.Text        `json:"summary"`
	OrganizationID  pgtype.UUID        `json:"organization_id"`
}

type MeetingActionItem struct {
	ID               pgtype.UUID        `json:"id"`
	MeetingID        pgtype.UUID        `json:"meeting_id"`
	Task             string             `json:"task"`
	Assignee         pgtype.Text        `json:"assignee"`
	TimestampSeconds float64            `json:"timestamp_seconds"`
	Completed        bool               `json:"completed"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type MeetingDecision struct {
	ID               pgtype.UUID        `json:"id"`
	MeetingID        pgtype.UUID        `json:"meeting_id"`
	Decision         string             `json:"decision"`
	TimestampSeconds float64            `json:"timestamp_seconds"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Organization struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Domain    pgtype.Text        `json:"domain"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OrganizationMember struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Role           UserRole           `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TranscriptChunk struct {
	ID        pgtype.UUID        `json:"id"`
	MeetingID pgtype.UUID        `json:"meeting_id"`
	Chunk     string             `json:"chunk"`
	Embedding pgvector_go.Vector `json:"embedding"`
}

type TranscriptSegment struct {
	ID        pgtype.UUID        `json:"id"`
	MeetingID pgtype.UUID        `json:"meeting_id"`
	StartTime float64            `json:"start_time"`
	EndTime   float64            `json:"end_time"`
	SpeakerID string             `json:"speaker_id"`
	Speaker   pgtype.Text        `json:"speaker"`
	Text      string             `json:"text"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
