// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// db/queries/meetings.sql
	CreateMeeting(ctx context.Context, arg CreateMeetingParams) (Meeting, error)
	CreateMeetingActionItem(ctx context.Context, arg CreateMeetingActionItemParams) (MeetingActionItem, error)
	CreateMeetingDecision(ctx context.Context, arg CreateMeetingDecisionParams) (MeetingDecision, error)
	// db/queries/transcripts.sql
	CreateTranscriptSegment(ctx context.Context, arg CreateTranscriptSegmentParams) (TranscriptSegment, error)
	DeleteMeeting(ctx context.Context, id pgtype.UUID) error
	DeleteMeetingActionItem(ctx context.Context, id pgtype.UUID) error
	DeleteMeetingActionItems(ctx context.Context, meetingID pgtype.UUID) error
	DeleteMeetingDecision(ctx context.Context, id pgtype.UUID) error
	DeleteMeetingDecisions(ctx context.Context, meetingID pgtype.UUID) error
	DeleteTranscriptSegment(ctx context.Context, id pgtype.UUID) error
	DeleteTranscriptSegmentsByMeeting(ctx context.Context, meetingID pgtype.UUID) error
	GetMeeting(ctx context.Context, id pgtype.UUID) (Meeting, error)
	GetMeetingActionItem(ctx context.Context, id pgtype.UUID) (MeetingActionItem, error)
	GetMeetingDecision(ctx context.Context, id pgtype.UUID) (MeetingDecision, error)
	GetTranscriptSegment(ctx context.Context, id pgtype.UUID) (TranscriptSegment, error)
	ListIncompleteActionItems(ctx context.Context, meetingID pgtype.UUID) ([]MeetingActionItem, error)
	ListMeetingActionItems(ctx context.Context, meetingID pgtype.UUID) ([]MeetingActionItem, error)
	ListMeetingDecisions(ctx context.Context, meetingID pgtype.UUID) ([]MeetingDecision, error)
	ListMeetings(ctx context.Context) ([]Meeting, error)
	ListMeetingsWithDecisionsAndActionItems(ctx context.Context) ([]ListMeetingsWithDecisionsAndActionItemsRow, error)
	ListTranscriptSegments(ctx context.Context, meetingID pgtype.UUID) ([]TranscriptSegment, error)
	MarkActionItemCompleted(ctx context.Context, id pgtype.UUID) (MeetingActionItem, error)
	MarkActionItemIncomplete(ctx context.Context, id pgtype.UUID) (MeetingActionItem, error)
	UpdateMeeting(ctx context.Context, arg UpdateMeetingParams) (Meeting, error)
	UpdateMeetingActionItem(ctx context.Context, arg UpdateMeetingActionItemParams) (MeetingActionItem, error)
	UpdateTranscriptSegment(ctx context.Context, arg UpdateTranscriptSegmentParams) (TranscriptSegment, error)
}

var _ Querier = (*Queries)(nil)
