// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transcripts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTranscriptSegment = `-- name: CreateTranscriptSegment :one
INSERT INTO
    transcript_segments (meeting_id, start_time, end_time, speaker, text)
VALUES
    ($1, $2, $3, $4, $5)
RETURNING
    id, meeting_id, start_time, end_time, speaker, text, created_at
`

type CreateTranscriptSegmentParams struct {
	MeetingID pgtype.UUID `json:"meeting_id"`
	StartTime float64     `json:"start_time"`
	EndTime   float64     `json:"end_time"`
	Speaker   string      `json:"speaker"`
	Text      string      `json:"text"`
}

// db/queries/transcripts.sql
func (q *Queries) CreateTranscriptSegment(ctx context.Context, arg CreateTranscriptSegmentParams) (TranscriptSegment, error) {
	row := q.db.QueryRow(ctx, createTranscriptSegment,
		arg.MeetingID,
		arg.StartTime,
		arg.EndTime,
		arg.Speaker,
		arg.Text,
	)
	var i TranscriptSegment
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.StartTime,
		&i.EndTime,
		&i.Speaker,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTranscriptSegment = `-- name: DeleteTranscriptSegment :exec
DELETE FROM transcript_segments
WHERE
    id = $1
`

func (q *Queries) DeleteTranscriptSegment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTranscriptSegment, id)
	return err
}

const deleteTranscriptSegmentsByMeeting = `-- name: DeleteTranscriptSegmentsByMeeting :exec
DELETE FROM transcript_segments
WHERE
    meeting_id = $1
`

func (q *Queries) DeleteTranscriptSegmentsByMeeting(ctx context.Context, meetingID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTranscriptSegmentsByMeeting, meetingID)
	return err
}

const getTranscriptSegment = `-- name: GetTranscriptSegment :one
SELECT
    id, meeting_id, start_time, end_time, speaker, text, created_at
FROM
    transcript_segments
WHERE
    id = $1
LIMIT
    1
`

func (q *Queries) GetTranscriptSegment(ctx context.Context, id pgtype.UUID) (TranscriptSegment, error) {
	row := q.db.QueryRow(ctx, getTranscriptSegment, id)
	var i TranscriptSegment
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.StartTime,
		&i.EndTime,
		&i.Speaker,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const listTranscriptSegments = `-- name: ListTranscriptSegments :many
SELECT
    id, meeting_id, start_time, end_time, speaker, text, created_at
FROM
    transcript_segments
WHERE
    meeting_id = $1
ORDER BY
    start_time ASC
`

func (q *Queries) ListTranscriptSegments(ctx context.Context, meetingID pgtype.UUID) ([]TranscriptSegment, error) {
	rows, err := q.db.Query(ctx, listTranscriptSegments, meetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranscriptSegment{}
	for rows.Next() {
		var i TranscriptSegment
		if err := rows.Scan(
			&i.ID,
			&i.MeetingID,
			&i.StartTime,
			&i.EndTime,
			&i.Speaker,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTranscriptSegment = `-- name: UpdateTranscriptSegment :one
UPDATE transcript_segments
SET
    text = $2,
    start_time = $3,
    end_time = $4,
    speaker = $5,
    updated_at = NOW()
WHERE
    id = $1
RETURNING
    id, meeting_id, start_time, end_time, speaker, text, created_at
`

type UpdateTranscriptSegmentParams struct {
	ID        pgtype.UUID `json:"id"`
	Text      string      `json:"text"`
	StartTime float64     `json:"start_time"`
	EndTime   float64     `json:"end_time"`
	Speaker   string      `json:"speaker"`
}

func (q *Queries) UpdateTranscriptSegment(ctx context.Context, arg UpdateTranscriptSegmentParams) (TranscriptSegment, error) {
	row := q.db.QueryRow(ctx, updateTranscriptSegment,
		arg.ID,
		arg.Text,
		arg.StartTime,
		arg.EndTime,
		arg.Speaker,
	)
	var i TranscriptSegment
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.StartTime,
		&i.EndTime,
		&i.Speaker,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}
