// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vectors.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const createTranscriptVectorEmbedding = `-- name: CreateTranscriptVectorEmbedding :one
INSERT INTO
    transcript_chunk (meeting_id, chunk, embedding)
VALUES
    ($1, $2, $3)
RETURNING
    id, meeting_id, chunk, embedding
`

type CreateTranscriptVectorEmbeddingParams struct {
	MeetingID pgtype.UUID        `json:"meeting_id"`
	Chunk     string             `json:"chunk"`
	Embedding pgvector_go.Vector `json:"embedding"`
}

// db/queries/vectors.sql
func (q *Queries) CreateTranscriptVectorEmbedding(ctx context.Context, arg CreateTranscriptVectorEmbeddingParams) (TranscriptChunk, error) {
	row := q.db.QueryRow(ctx, createTranscriptVectorEmbedding, arg.MeetingID, arg.Chunk, arg.Embedding)
	var i TranscriptChunk
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.Chunk,
		&i.Embedding,
	)
	return i, err
}

const getTranscriptVector = `-- name: GetTranscriptVector :many
SELECT
    id, meeting_id, chunk, embedding
FROM
    transcript_chunk
WHERE
    meeting_id = $1
`

func (q *Queries) GetTranscriptVector(ctx context.Context, meetingID pgtype.UUID) ([]TranscriptChunk, error) {
	rows, err := q.db.Query(ctx, getTranscriptVector, meetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranscriptChunk{}
	for rows.Next() {
		var i TranscriptChunk
		if err := rows.Scan(
			&i.ID,
			&i.MeetingID,
			&i.Chunk,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTranscriptChunk = `-- name: SearchTranscriptChunk :many
SELECT
    id,
    meeting_id,
    chunk,
    embedding <=> $1 AS distance
FROM
    transcript_chunk
WHERE
    meeting_id = $2
ORDER BY
    embedding <=> $1
LIMIT
    $3
`

type SearchTranscriptChunkParams struct {
	Embedding pgvector_go.Vector `json:"embedding"`
	MeetingID pgtype.UUID        `json:"meeting_id"`
	Limit     int32              `json:"limit"`
}

type SearchTranscriptChunkRow struct {
	ID        pgtype.UUID `json:"id"`
	MeetingID pgtype.UUID `json:"meeting_id"`
	Chunk     string      `json:"chunk"`
	Distance  interface{} `json:"distance"`
}

func (q *Queries) SearchTranscriptChunk(ctx context.Context, arg SearchTranscriptChunkParams) ([]SearchTranscriptChunkRow, error) {
	rows, err := q.db.Query(ctx, searchTranscriptChunk, arg.Embedding, arg.MeetingID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTranscriptChunkRow{}
	for rows.Next() {
		var i SearchTranscriptChunkRow
		if err := rows.Scan(
			&i.ID,
			&i.MeetingID,
			&i.Chunk,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
